import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

const config = [
    {
        ignores: [".next/**", "node_modules/**", "out/**", "build/**", "next-env.d.ts"],
    },
    ...nextCoreWebVitals,
    ...nextTypescript,
    {
        rules: {
            // shadcn/ui patterns generated by v0 trigger the new React 19 rules.
            // They are valid here, so we keep them as warnings rather than errors.
            "react-hooks/set-state-in-effect": "warn",
            "react-hooks/purity": "warn",
        },
    },
]

export default config
