[build]
builder = "nixpacks"
buildCommand = "pip install pipenv && cd backend && pipenv install --system --deploy"

[deploy]
startCommand = "cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Persistent storage for uploads
# Note: The volume "portafolio-volume" is manually created and attached in Railway Dashboard
# It should be mounted at /app/backend/uploads

