services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: portafolio_postgres_dev
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - portfolio_network

  # PgAdmin para administración de BD
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: portafolio_pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@portfolio.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5055:80"
    depends_on:
      - postgres
    networks:
      - portfolio_network

volumes:
  postgres_data:
    name: portafolio_postgres_data_dev

networks:
  portfolio_network:
    name: portafolio_network_dev
    driver: bridge
