version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres_prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network
    restart: unless-stopped

  # Backend FastAPI
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: portfolio_backend_prod
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "False"
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - portfolio_network
    restart: unless-stopped

volumes:
  postgres_data:
  backend_uploads:

networks:
  portfolio_network:
    driver: bridge
