"""add_cv_source_and_manual_cv_url_fields

Revision ID: 6dc55e48b75a
Revises: 4342489fe923
Create Date: 2025-10-03 17:35:06.374938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc55e48b75a'
down_revision: Union[str, Sequence[str], None] = '4342489fe923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_site_settings_id'), table_name='site_settings')
    op.drop_table('site_settings')
    op.add_column('cv', sa.Column('cv_source', sa.String(length=20), nullable=False, server_default='generated'))
    op.add_column('cv', sa.Column('manual_cv_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_column('cv', 'manual_cv_url')
    op.drop_column('cv', 'cv_source')
    op.create_table('site_settings',
    sa.Column('site_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('site_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('site_keywords', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hero_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('hero_subtitle', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hero_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hero_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hero_background_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('about_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('about_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('about_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('contact_form_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('seo_meta_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('seo_meta_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('seo_og_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('theme_primary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('theme_secondary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('theme_accent_color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dark_mode_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('google_analytics_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('projects_per_page', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_project_count', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('footer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('footer_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('maintenance_mode', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('maintenance_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('site_settings_pkey'))
    )
    op.create_index(op.f('ix_site_settings_id'), 'site_settings', ['id'], unique=False)
    op.create_table('analytics',
    sa.Column('page_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('page_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('visitor_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('session_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('os', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_pkey'))
    )
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    # ### end Alembic commands ###
