"""add_page_content_for_cms

Revision ID: 81f097efca04
Revises: add_user_roles_permissions
Create Date: 2025-10-01 10:00:45.900206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f097efca04'
down_revision: Union[str, Sequence[str], None] = 'add_user_roles_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_content',
    sa.Column('page_key', sa.String(length=100), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_edited_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_content_id'), 'pages_content', ['id'], unique=False)
    op.create_index(op.f('ix_pages_content_page_key'), 'pages_content', ['page_key'], unique=False)
    op.create_index(op.f('ix_pages_content_section_key'), 'pages_content', ['section_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_content_section_key'), table_name='pages_content')
    op.drop_index(op.f('ix_pages_content_page_key'), table_name='pages_content')
    op.drop_index(op.f('ix_pages_content_id'), table_name='pages_content')
    op.drop_table('pages_content')
    # ### end Alembic commands ###
